### ISSUE TITLE
"Short description" and "Description" are not very descriptive names for what users.

### ISSUE THREAD

**Issue by Drvanon** [GridtNetwork/gridt-client#72] opened 2020-04-18 18:32 UTC
It would be good if we could find names for these so that in the UI we can more clearly convey what we want the movement creator to write there. It is not necessary to change the code for this, just the labeling should do it.

**Comment by HendrikPreuter** [comment] 2020-09-07 10:31
It is also currently possible to leave the Description field blank. Should this become a required field or is this by design?

**Comment by Drvanon** [comment] 2020-09-07 11:06
> It is also currently possible to leave the Description field blank. Should this become a required field or is this by design?

This is currently by design. The short description is important in our opinion to understand the purpose, but we did not see the necessity of making a larger one required. Though feel free to argue your point.

**Comment by Drvanon** [comment] 2020-09-07 11:07
When assigning this to yourself, feel free to change the user interface, but do not change the models or the API, as that requires changes on the server as well. If you want to make a suggestion go ahead.

**Comment by HendrikPreuter** [comment] 2020-09-07 13:43
> > It is also currently possible to leave the Description field blank. Should this become a required field or is this by design?
> 
> This is currently by design. The short description is important in our opinion to understand the purpose, but we did not see the necessity of making a larger one required. Though feel free to argue your point.

I agree the short one is necessary, since this is also what draws people to the movement, the title doesn't always cut it.
I think you may be right to assume it is not required, altough i would argue we should try to encourage the users to do so as it can add a lot.

I was thinking about something like a dummy text or structure to help them.

Short description i feel speaks for itself.
However the detailed description might need some touching up.

**Comment by HendrikPreuter** [comment] 2020-09-07 13:44
> When assigning this to yourself, feel free to change the user interface, but do not change the models or the API, as that requires changes on the server as well. If you want to make a suggestion go ahead.

i feel that UI changes might fall out of the scope of this issue, do they not?

**Comment by Drvanon** [comment] 2020-09-07 15:30
> > When assigning this to yourself, feel free to change the user interface, but do not change the models or the API, as that requires changes on the server as well. If you want to make a suggestion go ahead.
> 
> i feel that UI changes might fall out of the scope of this issue, do they not?

Depending on how big of a change you want to make feel free to make a suggestion. I would not overhaul the whole thing, but a few lines here and there should be fine.

**Comment by HendrikPreuter** [comment] 2020-09-08 09:44
Merged into api-development

**Closed** 2020-09-08 09:43 UTC
Labels: bug, good first issue
